### ISSUE TITLE
Prevent simultaneous translation of content

### ISSUE THREAD

**Issue by akjackson1** [AdventistCommons/adventistcommons.org#1]
In order to prevent on user from overwriting the translations of another, we should only allow one user to edit at a time. There's two way we could approach this: 

1.  On a paragraph-by-paragraph basis. This would require asynchronously updating the `product_content_status` table with the `user_id` and a `user_last_active` timestamp of whoever has their cursor in the textarea of the corresponding paragraph. At the same time, we would need to regularly check for updates on this frequently (every ~15-30 seconds?) in order to lock the textarea and prevent others from editing at the same time. This may be overkill, at least to begin with, and may be more prone to errors.

2. A less intensive option would be to create a `project_section_status` table and similarly store the `user_id` and `user_last_active` of whoever is viewing the editor for that section (https://github.com/AdventistCommons/adventistcommons.org/blob/master/application/controllers/Editor.php#L27 ). When another user tries to access the the page, they would be greeted with a message asking them to check back soon, or make the editor read only with a message indicating as such. 

Those seem to be the easiest approaches. I'm open to either option but would probably lean towards the latter. I'm also open to exploring other options.

**Comment by davrv93** [comment]
Hi @akjackson1!
Maybe this can be done using a socket connection.
For example, when a user connects to the editor page, it sends a request to the socket server, indicating that its currently on the page (the same for all the users that enter the page).
Every time a user is working on a paragraph you can send a new request to the resources API updating the paragraph status to "busy" also you can send the user_id.

The socket connection allows you to avoid the 15-20 seconds check, because you can send a socket message to all the users when the user finish to translate the paragraph.

Here I share you a link with an example and some explanation: https://nodesource.com/blog/understanding-socketio/

God bless you!

**Comment by dallas** [comment]
Here’s some more information about what WebSockets are and a list of tools that can be used to use them: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

**Comment by EzraEn1** [comment]
Could this issue be circumvented entirely with a review system? Just like Git, translators could work on their own paragraphs and submit them for review, where differing translations could be compared and further refined if needed. On the other hand, why isolate editing to a single user and paragraph? Paragraphs aren't always a guarantee, formatting could make it hard to differentiate separations, particularly in more obscure languages. The Google Docs-style of live, simultaneous collaboration also seems to work for an enterprise-grade software suite, has that been looked into as well?

**Comment by davrv93** [comment]
> Could this issue be circumvented entirely with a review system? Just like Git, translators could work on their own paragraphs and submit them for review, where differing translations could be compared and further refined if needed. On the other hand, why isolate editing to a single user and paragraph? Paragraphs aren't always a guarantee, formatting could make it hard to differentiate separations, particularly in more obscure languages. The Google Docs-style of live, simultaneous collaboration also seems to work for an enterprise-grade software suite, has that been looked into as well?

Also you can combine this solution with a socket server, for example you can show which users are editing the paragraph in realtime, by this way you can inform other users that someone is currently working on the paragraph. I can create a project with python and daphne that use sockets  and the php project can connect to the server with the ws protocol.

**Comment by akjackson1** [comment]
As I've thought about this some more, for our purposes I think it will suffice to simply have a "restore" function on the revisions section. This would allow a reviewer to choose which version to use if two translations were submitted at the same time. 

@davrv93 is this something that could be deployed on shared hosting? Don't want to over-engineer a potentially basic/insignificant issue. I have absolutely no experience with Python so not sure how involved this would be?

**Comment by akjackson1** [comment]
How about using http://socketo.me/ to handle the websocket?

**Comment by davrv93** [comment]
> As I've thought about this some more, for our purposes I think it will suffice to simply have a "restore" function on the revisions section. This would allow a reviewer to choose which version to use if two translations were submitted at the same time.
> 
> @davrv93 is this something that could be deployed on shared hosting

Well with sockets you can do lots of things like notifications (you can enable push notifications in your frontend), real time work and other things (for example prevent editing the same file, text) , the ram consumption, maybe in a future it could be helpful for other requirements so you can apply a solution like this in the future ! 
Sure you can use socketo.me and also it can be deployed in a shared hosting ( that lets you access to the terminal for install packages ) or self hosting.


Blessings!

**Comment by akjackson1** [comment]
@davrv93 totally agree, I think in the future it may be helpful but I don't think it's urgent at the moment. For now I'm going to close this issue.
