### ISSUE TITLE
More detail about how to volunteer/signup in README

### ISSUE THREAD

**Issue by dallas** [AdventistCommons/adventistcommons.org#11]
In the **Contribute** section of the README, only one of the ways in which people can contribute has a clickable call to action (the “Authors” section), but that call to action just lands you on the root adventistcommons.org page which doesn’t make it very clear how you actually get your name on a list. The “Artists” and “Graphic Designers” sections have similar calls to action but there is nothing to click on and no indication of _where_ such lists may exist.

**Comment by EzraEn1** [comment]
Would a link to GitHub's [Guide to Open Source](https://opensource.guide/how-to-contribute/) be appropriate for the Developer section?

**Comment by m-dotcom** [comment]
Thank you for your feedback on this. I added more information about this now. As soon as the site goes into beta testing people will be able to sign up.
