### ISSUE TITLE
Allow for rectangle product images

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#111]
Currently, only square images are supported. Allow for rectangle product images.

<img width="759" alt="Screen Shot 2020-03-16 at 11 26 32 AM" src="https://user-images.githubusercontent.com/51795720/76741962-1046ca80-6779-11ea-904e-8ac64e0ce8d7.png">

**Comment by vibby** [comment]
Fixed, but I did not see how the images appears

**Comment by m-dotcom** [comment]
Let me know when its live on develop and I will check...

**Comment by m-dotcom** [comment]
Excellent.
