### ISSUE TITLE
Enable adding of product series

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#112]
It seems there is a bug with adding a title for a product series.

<img width="722" alt="Screen Shot 2020-03-16 at 11 33 51 AM" src="https://user-images.githubusercontent.com/51795720/76742636-14271c80-677a-11ea-974f-6cce9771c4dd.png">

**Comment by vibby** [comment]
Series are not an arbitrary string, but an object. They will can be created in backend.
I create one for you on develop for test purpose.

**Comment by m-dotcom** [comment]
Where can they be created in the backend? Can an admin do that?

**Comment by vibby** [comment]
It exists, but not available on delevop yet

**Comment by m-dotcom** [comment]
Ok, will wait until you deploy it. I will test "series" later when you give me the go ahead.
