### ISSUE TITLE
Limit width of text area when translating

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#114]
When a user opens the editor and has a screen with wide dimensions, the text area extends beyond the width of the translation interface. For user experience it would be great if it could not extend further. 

Congratulations for the great work done by allowing the editor to adjust for smaller devices. Excellent. 

<img width="1154" alt="Screen Shot 2020-03-16 at 11 40 48 AM" src="https://user-images.githubusercontent.com/51795720/76743548-75032480-677b-11ea-96a9-23e169fcd2d0.png">

**Comment by vibby** [comment]
There is an extension limit. You see here it comes to an end :
![Capture d’écran de 2020-03-16 15-08-35](https://user-images.githubusercontent.com/1181902/76766493-60815500-6798-11ea-9856-cd5fdc9ecc37.png)

Or I misunderstand you ?

**Comment by m-dotcom** [comment]
Why not make the extension limit same as translation interface extension limit?

**Comment by vibby** [comment]
I do no know, it was done like that, it sounds nice to me …

**Comment by m-dotcom** [comment]
Looks great.
