### ISSUE TITLE
Bug: Deleting existing product

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#115]
It is currently not possible to delete an existing product. Following error appears:

<img width="673" alt="Screen Shot 2020-03-16 at 11 47 46 AM" src="https://user-images.githubusercontent.com/51795720/76743938-1ab69380-677c-11ea-813c-c314087d53b8.png">

**Comment by vibby** [comment]
I repeat it on my environment. It’s a deletion in database that breaks relation to projects, etc.
We should add "on detele: cascade" in db relations.

@m-dotcom, should we give a warning to user that all current translations of the product in any language will be lost, giving the number of translated sentences ?

**Comment by m-dotcom** [comment]
Good idea, I think it would be important for the Admin to know when a product is deleted.

**Comment by m-dotcom** [comment]
Problem still exists

**Comment by vibby** [comment]
I forgot to add the remove cascade link with download logs and associated attachments. Should be ok

**Comment by m-dotcom** [comment]
Just tried. Problem still persists.

**Comment by vibby** [comment]
You

**Comment by vibby** [comment]
It’s a problem of data, we had many products with the same slug «hope», created a long time ago.
Now, it is impossible to create it anymore, but before it was possible.

I removed them manually from database.
Please, test again.

**Comment by m-dotcom** [comment]
Perfect.
