### ISSUE TITLE
IDML Parsing Bugs?

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#116]
IDML parsing is working very well, but once every so often I find a bug. See below for chapter 2 of the test product we created. We have have to fix this in InDesign but just wanted to bring it up to verify. 

<img width="510" alt="Screen Shot 2020-03-16 at 11 50 17 AM" src="https://user-images.githubusercontent.com/51795720/76744212-90bafa80-677c-11ea-93e5-690129d623d5.png">

<img width="485" alt="Screen Shot 2020-03-16 at 11 49 51 AM" src="https://user-images.githubusercontent.com/51795720/76744218-91ec2780-677c-11ea-955a-eae3e8c1502d.png">

**Comment by vibby** [comment]
It’s an error in idml.
Line 631 of Story_u1a7.xml :
```
						<Br />
						<Content>John 14:26, 27 puts it this way: “But the Helper, the Holy Spirit, whom the Father will send in My Name, He will teach you all things, and bring to your remembran</Content>
						<Content>ce all things that I said to you. Peace I leave with you, My peace I give to you; not as the world gives do I give to you.”</Content>
						<Br />
```

**Comment by m-dotcom** [comment]
Thanks. I will leave this issue open and take a look later at the IDML.

**Comment by vibby** [comment]
I can also propose you to refuse an idml if it has two contents tags collpased without a Br between the two.

**Comment by vibby** [comment]
Done. IDML validation will refuse it.

**Comment by m-dotcom** [comment]
This seems to be working now. I think it would be good if we could make a product invisible to users, this way we can check all the parsing in the editor and make sure everything is in the right place before people start translating it. Once they translate we cannot make any changes anymore. What do you think about that?

**Comment by m-dotcom** [comment]
Excellent job done! All is working now with the parsing it seems. We are just making a few changes to the IDML itself. Regarding making products invisible (see above), it is not needed for beta.
