### ISSUE TITLE
UX Improvement: Click to Remove Text

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#117]
When a user clicks to translate a sentence (see screenshot), the text to translate appears in the translation box. This is perfect. However, the user is required to delete the text before translating. To speed up the process, is it possible that as soon as you click in the box the text disappears?

<img width="1121" alt="Screen Shot 2020-03-16 at 11 59 09 AM" src="https://user-images.githubusercontent.com/51795720/76745265-40dd3300-677e-11ea-9ed0-92e158017164.png">

**Comment by vibby** [comment]
As a side effect, translated content now appears in red if translated

**Comment by m-dotcom** [comment]
Excellent job!
