### ISSUE TITLE
UX Improvement: Enter to submit

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#118]
To speed up the translation process, it would be great if when a user hits "enter" on his keyboard he automatically submits the translation and it moves him automatically to the next sentence to translate. This would save a significant amount of time for the translator.

Not sure if possible, but if they could also move up and down with their keyboard arrows to different sentences that would be amazing!

**Comment by vibby** [comment]
It is not a good idea with arrows. Users do not think it will act taht way, but go on privious / next line of the content. Maybe we try to find a combinasion like ctrl-up / ctrl-down. To be tested…

**Comment by m-dotcom** [comment]
Fine with me. But "enter" should definitely save the translation and move to the next line.

**Comment by vibby** [comment]
I added the «enter» and also the shortcuts «ALT+UP» and «ALT+DOWN»

**Comment by m-dotcom** [comment]
Really excellent! Great job done!
