### ISSUE TITLE
UI Improvement: "Translate" and "Statistic" Button

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#119]
Translate Button: The normal user probably does not need to see the "translate button" (see screenshot). This becomes relevant for those users who have proofread and review permission and can switch between them. 

Statistic Button: Users can see statistics when clicking on the top right of the translation interface. The statistics slides out, but the button seems to be invisible (see screenshot). 

<img width="102" alt="Screen Shot 2020-03-16 at 12 13 30 PM" src="https://user-images.githubusercontent.com/51795720/76746330-01174b00-6780-11ea-829b-814231558103.png">

<img width="921" alt="Screen Shot 2020-03-16 at 12 16 01 PM" src="https://user-images.githubusercontent.com/51795720/76746373-14c2b180-6780-11ea-8bea-6c5f209c9280.png">

**Comment by vibby** [comment]
Please open another issue for stats, data are not right in them. Shall be show stats of product or project or chapter ?

**Comment by m-dotcom** [comment]
I was thinking to show stats based on the section they are translating.

**Comment by m-dotcom** [comment]
Can't test this since my user has admin rights. Tried to register a new users, "translator", "proofreader", "reviewer", and "admin" to test different functions, but am getting an error when signing up. Will open a new issue about this

**Comment by m-dotcom** [comment]
Is email service functioning now?

**Comment by vibby** [comment]
No, I do not have any idea on how to set it up, what service to use. Here is a limit of my knowledge ! If you count on me only, it can take a month.

**Comment by m-dotcom** [comment]
There seems to be an issue with the roles somehow when I open the editor:

<img width="1233" alt="Screen Shot 2020-03-17 at 8 00 48 PM" src="https://user-images.githubusercontent.com/51795720/76886883-137dab80-688a-11ea-9d80-150c27aff97a.png">

**Comment by vibby** [comment]
Hey @m-dotcom, please, open new issues ! We have 3 or 4 topics in this one !

**Comment by vibby** [comment]
Can we close this one about «hide trnaslator button if alone» and «show the stats button» (wow, that makes two issues ;))

**Comment by m-dotcom** [comment]
OK.
