### ISSUE TITLE
Project installation Instructions on README file.

### ISSUE THREAD

**Issue by rafaelji** [AdventistCommons/adventistcommons.org#12]
Maybe for PHP developers, it's kinda obvious how to set up the project after cloning to own pc, but for front-end developers like me, it's not that obvious. I think that would be great if at the README file there was something like an "Installation step-by-step" section, showing all necessary commands to make the local project ready to start working, like composer install, run migrations and so on. What do you think about it?

**Comment by akjackson1** [comment]
Yes! I've been planning on doing that, thanks for creating this issue as a reminder 👍

**Comment by akjackson1** [comment]
I've added some basic instructions [here](https://github.com/AdventistCommons/adventistcommons.org/blob/master/README.md#development-setup-guide). Let me know if I missed anything. I'm sure I'll think of other stuff to add.

**Comment by rafaelji** [comment]
Thanks @akjackson1! I'm not sure but shouldn't it have a `composer install` command? And about the front-end assets, how we going to build they? Will we use Yarn? Maybe add a `yarn install` command?
