### ISSUE TITLE
Bug: Download English PDFs

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#121]
I get an error when downloading the English sample PDF files I uploaded:

<img width="988" alt="Screen Shot 2020-03-16 at 12 31 27 PM" src="https://user-images.githubusercontent.com/51795720/76747692-37ee6080-6782-11ea-8bea-a26a5534e272.png">

**Comment by vibby** [comment]
It works for me. Did you try it with pdf you just uploaded or it was here since a long time ?

**Comment by m-dotcom** [comment]
Will look at it again later today!

**Comment by m-dotcom** [comment]
Seems to work for me now also. Thanks.
