### ISSUE TITLE
Bug: Product Image Not Showing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#128]
Product image uploaded but not showing. See below. 

<img width="473" alt="Screen Shot 2020-03-17 at 10 22 26 AM" src="https://user-images.githubusercontent.com/51795720/76836308-48154700-6839-11ea-892d-d174721c109b.png">

**Comment by m-dotcom** [comment]
Re-uploaded the image but issue remains.

**Comment by vibby** [comment]
Please upload a new cover image to check the full feature

**Comment by m-dotcom** [comment]
Perfect. Works great.
