### ISSUE TITLE
Set up Docker environment for local development

### ISSUE THREAD

**Issue by rafaelji** [AdventistCommons/adventistcommons.org#13]
What if we start to use [Docker](https://www.docker.com/docker-community) as our local development?

 This way we could make sure that everybody has the same environment and avoid situations like "on my pc this new feature works!". I'm not fully experienced with Docker set up itself, but at my job we use Docker and I can share a configuration that works for PHP and Symfony framework, and by what I know, it can works for CodeIgniter too. Also, it can avoid us to install things directly on our own pcs, make the development servers more easy to start with just some command lines like `docker-compose up -d` and in the future the CI/CD process will become more automatic and faster.

What do you think?

**Comment by akjackson1** [comment]
@rafaelji this could be a helpful addition. I must say, I've used Docker in the past and was not too impressed, and I found it to run very poorly on my machine. Are there any more lightweight alternatives? Either way, if you're able to get something going that works well, that would be appreciated. Is that something you're able to work on?

I'm currently using DeployHQ to deploy through SFTP to my server (currently shared hosting). I'm not sure how deployment to a docker environment works.

**Comment by msands** [comment]
You wouldn't be deploying to a docker environment.  Docker would just be used for local development.  You can keep the same deployment process for going into production, but any developer that would like to improved upon your project as well as those wanting to test, will be guaranteed to all be working from the same development environment if docker is used.

@rafaelji , I haven't looked at the full code yet (and granted i'm not a php developer), but unless there's also a database hooked up for this project, `docker-compose` might not be necessary, "regular" `docker` could probably be fine.

Also, i was sent an invite to the project (from @m-dotcom), then the invite was revoked...

**Comment by davrv93** [comment]
Docker its really useful! I use it for my local, dev and prod environments, their adventages are :
 * Allows to create some configurations for local, dev and prod environments.
 * Helps to deploy and CI, (maybe we can think in this for the future, software like Jenkins its really helpful to deploy changes from branches
 * Shorter time of induction to the project.

**Comment by rafaelji** [comment]
I'm thinking in add an initial Docker configuration that works so everybody can analyze and comment about it at the pull request, but I need to know what commands are needed to start the local environment. I saw that @akjackson1 added the [development setup guide](https://github.com/AdventistCommons/adventistcommons.org/blob/master/README.md#development-setup-guide) section at the README file but I think that some things are missing. There's only a command to update the composer.lock file (**please correct me if I'm wrong**). What do you think about?

**Comment by msands** [comment]
Well, in any event, i'll submit a PR to add `docker` as well as update the README for those that chose to use the docker installation.

**Comment by m-dotcom** [comment]
@akjackson1 can you respond to @msands as to the verifications of the steps to install docker?

**Comment by m-dotcom** [comment]
@akjackson1 can you respond to @msands as to the verifications of the steps to install docker?

**Comment by akjackson1** [comment]
@msands sorry I somehow missed your comment. I have slightly updated the development steps. If you come across anything I've missed, let me know.

**Comment by akjackson1** [comment]
Closing this since we're now managing all our tasks on [Trello](https://trello.com/invite/b/cCdSmpc0/4527547fa5dedeee84a0ccae33d08865/adventist-commons-development).
