### ISSUE TITLE
Bug: "Skills" Label Missing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#131]
"Skills" label missing in account profile.

<img width="717" alt="Screen Shot 2020-03-17 at 4 12 05 PM" src="https://user-images.githubusercontent.com/51795720/76864678-2a140a80-686a-11ea-98c6-55d5b5c97abb.png">

**Comment by vibby** [comment]
Already done, I saw it with #120 and fixed it here : 001d6be733dcfe37224f80e42b293e54747d4557

**Comment by m-dotcom** [comment]
Great.
