### ISSUE TITLE
"My Project" Function

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#133]
I believe you are still working on this specific function in the user/translator dashboard, correct?

<img width="1079" alt="Screen Shot 2020-03-17 at 7 55 31 PM" src="https://user-images.githubusercontent.com/51795720/76886306-483d3300-6889-11ea-8d10-1f731451033b.png">

**Comment by vibby** [comment]
No.
As it was done before, an admin has to define manually who are the users on a project.
On page http://develop.adventistcommons.org/en/products/hope-beyond-tomorow/project/fre#members, you have an icon button to had a member to a project.
Should it be different ?

**Comment by vibby** [comment]
To be clear I implement this :
- Show project the user has participate to in the first array
- Show all project that are in the language the user knows, but he never participate to

**Comment by m-dotcom** [comment]
Excellent job.
