### ISSUE TITLE
"Role" in Translation Editor

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#134]
It seems that there is an error with the "role" attribution in the translation editor. 

<img width="1233" alt="Screen Shot 2020-03-17 at 8 00 48 PM" src="https://user-images.githubusercontent.com/51795720/76887243-a4ed1d80-688a-11ea-8092-d99f6659ff1b.png">

**Comment by vibby** [comment]
I cannot repeat that error. Can you tell me steps to reproduce ?

**Comment by m-dotcom** [comment]
It gives me this error whenever I open the editor and want to translate.

**Comment by vibby** [comment]
Got it. It happens when click on sae with user that does not have proofread nor review rights on language

**Comment by m-dotcom** [comment]
Thanks. Well done!
