### ISSUE TITLE
Add contributors to "contributor section"

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#135]
As soon as someone adds a translation to a specific product language, his name should be added to the "contributor" section. You may be aware of this already but didn't have time to work on it yet.

<img width="1029" alt="Screen Shot 2020-03-18 at 4 04 10 PM" src="https://user-images.githubusercontent.com/51795720/76968784-221f9d80-6932-11ea-9c59-a95d1b324936.png">

**Comment by vibby** [comment]
It’s the same as https://github.com/AdventistCommons/adventistcommons.org/issues/133
I tough it should be like like it was before : a user have to set members of a project.
I will do it based on participation.

**Comment by m-dotcom** [comment]
Anyone who is signed up can translate and is automatically assigned as a contributor.

**Comment by vibby** [comment]
Ok but there was a system to «invite» member to a project, prexisting before me. It should not exists ?

**Comment by m-dotcom** [comment]
Adam wanted to have a way where people can also be invited to projects, so if possible we should leave that also

**Comment by m-dotcom** [comment]
Perfect.
