### ISSUE TITLE
"My Projects" in Account Profile

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#136]
If someone contributed to a project and the project is not completed yet, it should appear under "My Projects" in his profile. Also, I think you probably know that but didn't have time yet to work on it.

<img width="1146" alt="Screen Shot 2020-03-18 at 4 06 51 PM" src="https://user-images.githubusercontent.com/51795720/76969026-82164400-6932-11ea-9896-40501a5d4576.png">

**Comment by vibby** [comment]
Isn’t that issue the same as https://github.com/AdventistCommons/adventistcommons.org/issues/133

**Comment by m-dotcom** [comment]
Oops.
