### ISSUE TITLE
Stats calculation in editor

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#138]
Set the real stas calculation into he editor page

**Comment by vibby** [comment]
@m-dotcom I have questions about stats. Do we consider a translation reviewed if a previous version was validated but not the last one.

Here is process :
- A contributor translate a sentence => translated % is lifted
- A proofreader mark it as validated => validated % is lifted
- The contributor (or another) modify the translation => validated % is raised ?

**Comment by m-dotcom** [comment]
If I understand you correctly, then yes. Process:

Contributed translates a sentence => translation % increased
Proofreader approves a sentences => proofread % increased
Reviewer approves sentence => reviewed % increased

**Comment by vibby** [comment]
No you get it. The question is : when another translation is proposed but not approved yet, do we already count it as approved ?

**Comment by m-dotcom** [comment]
"When another translation is proposed but not approved yet, do we already count it as approved?" 
I do not understand it, sorry...

**Comment by vibby** [comment]
To take a use case :
* A contributor translate a sentence => translated % is INcreased
* A proofreader mark it as approved => validated % is INcreased
* The contributor (or another) modify the translation => So the last translation is not approved yet => validated % is DEcreased ? or do not change ?

**Comment by m-dotcom** [comment]
In that case the percentage doesn't have to change because we simply replace translation for a more accurate one.

**Comment by vibby** [comment]
Ok, this is what I did.

**Comment by m-dotcom** [comment]
Cannot test it as I get an error when trying to access the product "Hope Beyond Tomorrow".

**Comment by vibby** [comment]
My bad

**Comment by m-dotcom** [comment]
Is it possible to update stats without having to reload the page - instant update?

**Comment by vibby** [comment]
Javascript part can become ugly. We need a real frontend developer to manage that in a correct way.
To answer you, it is possible, but if we continue that way we make a thing hard to understand and to maintain.

**Comment by m-dotcom** [comment]
Ok, lets leave it as it is for now.
