### ISSUE TITLE
Title and Author Dropdown

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#139]
Do you think we should make for "title" and "author" the same kind of "type or select from list box?"

<img width="1009" alt="Screen Shot 2020-03-19 at 3 06 50 PM" src="https://user-images.githubusercontent.com/51795720/77070650-4c855f80-69f3-11ea-8c26-6eb0d28faa7d.png">

**Comment by vibby** [comment]
It could be very cost in loading if there are many products. More over, I am afraid people think they cannot search a simple word because the system will propose full titles only.

**Comment by m-dotcom** [comment]
Ok. If needed we can also address it later.
