### ISSUE TITLE
Language Selector Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#140]
"Available in" does not show languages but some other information....

<img width="601" alt="Screen Shot 2020-03-19 at 3 06 16 PM" src="https://user-images.githubusercontent.com/51795720/77070760-7c346780-69f3-11ea-8866-d2d86f396717.png">

**Comment by vibby** [comment]
I tought it was about the serie :)

**Comment by m-dotcom** [comment]
Great work done..
