### ISSUE TITLE
New Product

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#141]
I get the following error when creating a new product. Could it be because of a faulty IDML?

<img width="650" alt="Screen Shot 2020-03-19 at 3 27 26 PM" src="https://user-images.githubusercontent.com/51795720/77072315-2ca36b00-69f6-11ea-9fbc-6fff52b01c57.png">

**Comment by vibby** [comment]
Can you send me the idml please ?

**Comment by vibby** [comment]
Validation of Idml gives me the message error :
```
Story u1df :
Two following paragraphs have the same style : «8)Dr. Ghassan Darwiche, head of the …».
Two following paragraphs have the same style : «• Fried Foods: Exchange fried foods, …». 
```

**Comment by m-dotcom** [comment]
Just tried to make a test. Somehow am getting this error:

<img width="563" alt="Screen Shot 2020-03-19 at 9 24 24 PM" src="https://user-images.githubusercontent.com/51795720/77106630-157d7100-6a28-11ea-9e61-bbdefceb7906.png">

**Comment by vibby** [comment]
This is a report error from Idml parsing. Every section must have a different name. In this file, two section have the same which is «Text».
You can obtain a report of all idml errors with the feature «Validate IDML»

**Comment by m-dotcom** [comment]
Ok, will try to get a new file for testing.

**Comment by m-dotcom** [comment]
Works now. Excellent job.
