### ISSUE TITLE
Accounts for Testing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#145]
As we continue with different dashboard and editor functions it may be good to setup the following accounts for temporary testing purposes only and assign the appropriate rights to these accounts.

Email: translator@adventistcommons.org
Pass: translator

Email: proofreader@adventistcommons.org
Pass: proofreader

Email: reviewer@adventistcommons.org
Pass: reviewer

Email: admin@adventistcommons.org
Pass: admin

**Comment by vibby** [comment]
Done. Please not that I made proofreader and reviewer able to approve / review only french and german languages

**Comment by m-dotcom** [comment]
Perfect. Excellent.
