### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#146]
It seems that when a sentence is translated in doesn't register that yet in overview of all the sections:

<img width="110" alt="Screen Shot 2020-03-23 at 10 16 57 AM" src="https://user-images.githubusercontent.com/51795720/77295988-8609e380-6cef-11ea-8ced-75a9b43a2c5d.png">

Also, it appears that progress tracking (color and paragraph) of the entire project is not working yet.

<img width="990" alt="Screen Shot 2020-03-23 at 10 17 06 AM" src="https://user-images.githubusercontent.com/51795720/77295991-87d3a700-6cef-11ea-8ed8-8ab5db3c45ef.png">

**Comment by vibby** [comment]
Actually, it was working, but showing approved translations, not just translations. I changed that.

**Comment by m-dotcom** [comment]
Yes, I think the larger progress bar can show multiple colors and track the progress of translation, proofreading, and review all at once...

**Comment by vibby** [comment]
For bars, it was already the case, but it was rounded so it was at Zero.
I also changed it for the number.

**Comment by m-dotcom** [comment]
Ok

**Comment by m-dotcom** [comment]
Excellent job!
