### ISSUE TITLE
Interface to define languages a user can approve and review

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#149]
Inside the admin

**Comment by m-dotcom** [comment]
Accessed with admin and get only the following:

<img width="688" alt="Screen Shot 2020-03-26 at 7 39 29 AM" src="https://user-images.githubusercontent.com/51795720/77614209-4cc2b500-6f35-11ea-96bd-98d6b075ac5c.png">

**Comment by vibby** [comment]
see #137

**Comment by m-dotcom** [comment]
Wow, great job Vincent.
