### ISSUE TITLE
Create a Slack workspace to facilitate the communications between us

### ISSUE THREAD

**Issue by rafaelji** [AdventistCommons/adventistcommons.org#15]
Guys, what you think about a Slack workspace so we can take our decisions faster? I know we already use the email and the issues area here, but with an Slack workspace, it will improve the way we talk and discuss some things.

**Comment by msands** [comment]
I agree with this.

It's free and i've had to administer a few slack organizations personally as well as one of the admins for slack here at work.

**Comment by asarmiento** [comment]
Si de acuerdo,

compartan el link para conectarnos nada mas cuando ya lo tengan creada la cuenta.

**Comment by akjackson1** [comment]
Done! https://join.slack.com/t/adventistcommons/shared_invite/enQtNjYzNjAxNTUwMzA1LTEzOTRlMzZkY2ZjYTlmZTRlYThmNzZhMjMxNmQ1NWE5MWNmZDEwYjE3YTA1YWVkMTFmYmQ5YzE5NjIwMGM0MjM

**Comment by rafaelji** [comment]
Thanks @akjackson1 ! :)
