### ISSUE TITLE
Proofreader Dashboard

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#150]

**Comment by m-dotcom** [comment]
Great Vincent. I think we need to simplify the dashboards later, but this is not important now. Functionality is all working so that is perfect.

**Comment by vibby** [comment]
Ok @m-dotcom. Could be good to check the wording too because am I not an english native :)

**Comment by m-dotcom** [comment]
Yes :), but I will do all the grammatical corrections at the very end. Let's focus on functions for now.
