### ISSUE TITLE
Show "Publisher" on Product Page

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#152]
It will be very important for us to show the publisher of each product so we can give those organization credit (would be create if this text could also be a link to their website in target=new window mode). See a suggestion below.

<img width="636" alt="Screen Shot 2020-03-30 at 6 25 43 PM" src="https://user-images.githubusercontent.com/51795720/77930960-33fb2c00-72b4-11ea-8038-9ba2a03c459b.png">

**Comment by m-dotcom** [comment]
I think you can take out the "Pages: X" placeholder, since people can see that in another place and we don't have enough space in there. 

Would be great if you can make the background of the below a little lighter :-). Otherwise, excellent work Vincent.

<img width="225" alt="Screen Shot 2020-03-31 at 6 26 35 PM" src="https://user-images.githubusercontent.com/51795720/78044367-41301d80-737d-11ea-9f7a-275bedb08e06.png">

**Comment by vibby** [comment]
I removed the page count. Please, gather all you remarks in the issue, not discovering them step by step along the treatment. It finally has not point with the editor name.

For the color, I think we should not get away from bootstrap stuff. We could lose constistency and maintenability very fast. Colors available are : https://getbootstrap.com/docs/4.4/utilities/colors/#background-color

**Comment by m-dotcom** [comment]
Use .bg-light for background text then...

**Comment by m-dotcom** [comment]
Thanks
