### ISSUE TITLE
Product IDML Replacement

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#153]
It takes me some time to make a new product and add all relevant information into the system. Then, when I look through how to IDML was parsed I make manual changes at times to the IDML. This required me to delete and recreate the product again, with all information. 

If there is a fast way for you to implement that we can replace the IDML and reparse, that would be great. If it is too much work right now then don't worry about it and I will continue as we have.

**Comment by vibby** [comment]
I added it as the feature : «remove all section / paragraphs / sentences / translations / idm file of product»

**Comment by m-dotcom** [comment]
Perfect Vincent. Works and makes working with products much much easier. Thank you for that.
