### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#154]
Don't know if there is a fast way to activate breadcrumbs, but if so it would be helpful, especially when you are in the editor and want to go back to the list of all languages of a product. If it takes too long to implement we can do that after beta.

**Comment by vibby** [comment]
I added a minimal breadcrumbs, No breadcrumb if only one item in it (list of product, list of projects, my account, etc.)

**Comment by m-dotcom** [comment]
Ok, let me know when I can test.

**Comment by vibby** [comment]
soon bro :)

**Comment by m-dotcom** [comment]
:-D... wow, that is perfect... huge help.
