### ISSUE TITLE
Reviewer Dashboard

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#156]
Dashboard where the reviewer can have access to:

    Projects
    Active projects(ongoing projects and new)- In this section the reviewer should have 3 tabs ("translator"," proofreader" and "reviewer") allowing to access active projects for all the roles
    Unassign button;
    Access to the reviewer guide;
    Project status: Each project goes through the following stages:
    i. Translation/Proofreading (these will be combined, because both activities can be completed simultaneously
    ii. Review of Manuscript
    iii. Design and Layout
    iv. Completed

    Contributions
    Access to projects that he had contributed(as translator, proofreader or reviewer)- this information should also be shown in a chart ,so it would be possible to the user see the evolution of his contributions in a determined period of time.
    In the summary of contributions, the information of: name of project,number of sentences that the user had translated/proofread/reviewed,date of completion of the project, should be displayed (see screenshot);

    Download history (see screenshot). When member download a PDF file for a project, it should be recorded in his dashboard (see screenshot).

**Comment by m-dotcom** [comment]
Great job. If you are a reviewer for a specific language, you automatically are also a proofreader, since you automatically have more rights. I think this must also be reflected in the dashboard.

**Comment by vibby** [comment]
done

**Comment by m-dotcom** [comment]
Perfect.
