### ISSUE TITLE
English Project Status

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#157]
I added an English PDF files to the develop environment. As illustrated below it appears that the English project status is not "ready to download," hence it still allows people to "translate" it in to English.

<img width="905" alt="Screen Shot 2020-04-01 at 2 46 36 PM" src="https://user-images.githubusercontent.com/51795720/78133711-9cb6e580-7427-11ea-9683-dad5e5c93ff4.png">

**Comment by vibby** [comment]
I gathered all download links in the dropdown : attached pdfs and download the idml translated.
I kept the button to translation interface but with the wording «fix translation»

**Comment by m-dotcom** [comment]
Actually, we will always have an English text and PDF first from which we move to the other languages, so in theory the project is also a product (English) in that sense. Since the product will also originate from the English language we will never translate into project "English". 

As soon as we complete a project and upload the PDF file, it should be closed for translation. However, I am thinking now that it may be helpful for admin or reviewer of the language to still have access to it in case any fix is needed, but not for the public. 

Hope it is clear.

**Comment by vibby** [comment]
So we should always have a project line for english language ? But never can translate that project ? Or we should not be able to choose english as language for a new translation ?

**Comment by m-dotcom** [comment]
Yes, the first line should always be the English line, but you can never translate into that language. And also, we should never be able to choose English as language for a new translation, you are right.

**Comment by vibby** [comment]
Can you tell me what is the meaning of that. There should be always an existing project in english ? or we should «fake» the view ? What is the interest of that line ? Could it be a property of the product : «original language» ?

**Comment by m-dotcom** [comment]
We don't have to have that line, but how can people download the English PDF otherwise?

**Comment by vibby** [comment]
![image](https://user-images.githubusercontent.com/1181902/78233075-80718200-74d5-11ea-99b8-e1663c666c6e.png)

Here is a proposition :
- The button "upload pdf file" near "Start new translation" open the same modal, but without the choice of the language. The attachment is associated to product.
- When a file is associated to product it can be downloaded from a button after the upload button.
- For every language, we add a button «upload result pdf» that opens a modal which looks the same as the previous modal.

That way, we avoid a selector for language because user choose language by the line.

**Comment by m-dotcom** [comment]
Ok, I think I understand and its fine with me. I hope I understand :-).

**Comment by vibby** [comment]
In addition, a reminder for me to set project as downloadable once a pdf is uploaded.
Question for you @m-dotcom : should we dissablow upload of pdf if project is not reviewed ?

**Comment by m-dotcom** [comment]
Not needed. Since we are admin we know not to do that. Lets get beta going :-)

**Comment by vibby** [comment]
Maybe it is not the feature you were looking for, but it is possible to upload files from product edit page. I hope I did not do that works twice :/ If true, that reveals we really need a product owner that **knows** the product from feature point of view …
Anyway. I did it. You can test it.

**Comment by m-dotcom** [comment]
Thanks Vincent. I think it is what we need for now. If we need improvement we can do it later after beta. Great job.
