### ISSUE TITLE
Reviewing Mode in Editor

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#158]
If the reviewer is logged in, currently there is no way to switch on the "review" function in the editor so we can test the dashboard.

<img width="578" alt="Screen Shot 2020-04-02 at 11 04 54 AM" src="https://user-images.githubusercontent.com/51795720/78224824-dfcd9300-74d1-11ea-81d9-1f912c836586.png">

**Comment by vibby** [comment]
Is your user able to review that language ?

Le 2 avril 2020 10:06:55 GMT+02:00, m-dotcom <notifications@github.com> a écrit :
>If the reviewer is logged in, currently there is no way to switch on
>the "review" function in the editor so we can test the dashboard.
>
><img width="578" alt="Screen Shot 2020-04-02 at 11 04 54 AM"
>src="https://user-images.githubusercontent.com/51795720/78224824-dfcd9300-74d1-11ea-81d9-1f912c836586.png">
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AdventistCommons/adventistcommons.org/issues/158

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by m-dotcom** [comment]
Not admin, not reviewer, and not fjdfdj@gmail.com

**Comment by vibby** [comment]
So it should be normal yo cannot review it, or I misunderstood ?

**Comment by m-dotcom** [comment]
reviewer and admin should have reviewer rights... when I login with reviewer and enter German language, its not possible to review... I hope I explained correctly :-)

<img width="669" alt="Screen Shot 2020-04-02 at 11 53 27 AM" src="https://user-images.githubusercontent.com/51795720/78229439-aa787380-74d8-11ea-8915-d870c1d934f7.png">

**Comment by vibby** [comment]
I understood you are «Not admin, not reviewer, and not fjdfdj@gmail.com» :)

**Comment by m-dotcom** [comment]
But Vincent, right now, no account can review, right?

**Comment by vibby** [comment]
I did it, it should be working now, if you define the language as reviewable by your user in the admin interface.

**Comment by m-dotcom** [comment]
Ok will test later.

**Comment by m-dotcom** [comment]
Logged in as reviewer and have review rights for German. But in editor I cannot switch to "review" mode. This is what I was trying to say, but maybe I am missing something :-)

<img width="484" alt="Screen Shot 2020-04-02 at 12 19 55 PM" src="https://user-images.githubusercontent.com/51795720/78232015-566f8e00-74dc-11ea-8c70-5f214b1cef34.png">

**Comment by vibby** [comment]
my bad

**Comment by m-dotcom** [comment]
Excellent
