### ISSUE TITLE
Create a board tasks

### ISSUE THREAD

**Issue by rafaelji** [AdventistCommons/adventistcommons.org#16]
I don't know if it already exists for this project, but in case no, it would be great for everyone if we have something like a kanban board with three or four columns like: To Do, In Progress, In Code Review and finished. 

This way I think that everybody will have an idea about individual and general progress. I'm saying it because, for example, at this moment I don't know what is really happening with the project general progress and If I can help with something.

We can use the board that Github provide or even better we can use the Trello that is also free and very good.

What you think about?

**Comment by asarmiento** [comment]
A mi me parece muy bien la idea para poder tener una orientación y así ya sepamos quien esta trabajando en cierta tarea y no se duplique, poder tener un rumbo por donde ir. 
@akjackson1 creo que eres el mas adecuado poder crearlo y poner las tareas para poder llegar a la meta u objetivo donde se quiere llegar.

**Comment by akjackson1** [comment]
We were already using a Trello board internally, so I copied over some of the items and made a trello board. I'm totally fine with primarily using this instead of the Issues, or using a combination of both. Whatever seems best. https://trello.com/b/cCdSmpc0/adventist-commons-development

**Comment by rafaelji** [comment]
Thanks @akjackson1 ! :)

**Comment by akjackson1** [comment]
Here's an invite link which will actually let you join the board and create cards, not just view and comment on them: https://trello.com/invite/b/6aSyzetB/eff6e13d9c874e7474d889ffec9afb09/adventist-commons-management
