### ISSUE TITLE
Reviewed Sentences Not Storing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#160]
I am just doing different tests and found that reviewed sentences become green, but upon closing the product and reopening the editor they are no longer marked.

<img width="1140" alt="Screen Shot 2020-04-02 at 12 59 07 PM" src="https://user-images.githubusercontent.com/51795720/78235780-cfbdaf80-74e1-11ea-9d26-5df98d5ad631.png">

**Comment by vibby** [comment]
Fixed

**Comment by m-dotcom** [comment]
Perfect Vincent!
