### ISSUE TITLE
Missing "Translation Mode" Switch in Editor

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#161]
The admin account currently has not "translation mode" switch in the editor.

<img width="592" alt="Screen Shot 2020-04-02 at 5 35 41 PM" src="https://user-images.githubusercontent.com/51795720/78261882-7c128c80-7508-11ea-8bf3-3f5642bad456.png">

**Comment by vibby** [comment]
Ok, I made it available even if someone is already proofreader or reviewer for the project.

**Comment by m-dotcom** [comment]
I was logged in with admin and the switch is still not showing.

**Comment by vibby** [comment]
Sorry, the last deployment did not finished correctly. It is now done.

**Comment by m-dotcom** [comment]
Cleared cache. Still not showing up.

**Comment by vibby** [comment]
my bad :/

**Comment by m-dotcom** [comment]
Perfect, well done.
