### ISSUE TITLE
Machine Translation for Re-Import to InDesign

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#162]
I am not sure if this is the right time to work on this, but let me describe why it would be helpful. I am doing extensive testing with importing IDML's with the correct settings. At times I need to manually adjust some details in the XML (after unzipping IDML) and before uploading it to the platform, because InDesign gets some details wrong, no matter how hard we work on adjusting it. That is all fine, but we would like to see if we translate the entire product and reimport it in InDesign, how the few XML changes to the IDML would affect the final translated IDML file (in German lets say). 

For that case it would be great if in the editor we had machine translation active, then we can just "translate" all into German or another language, export IDML, and test this. I am not sure how complicated it is to activate this feature now. If too much, then do not worry about now and I will manually test it with products. We can do it later, but I wanted to hear your opinion. 

<img width="1131" alt="Screen Shot 2020-04-02 at 5 37 18 PM" src="https://user-images.githubusercontent.com/51795720/78262427-399d7f80-7509-11ea-9710-4d44a5883fa9.png">

**Comment by vibby** [comment]
I have think about it a long time @m-dotcom, I cannot find a fast way to do it simply …

**Comment by m-dotcom** [comment]
Ok, we will do it later and I will work on it manually for now, don't worry. 

Thanks Vincent.
