### ISSUE TITLE
Product manager dashboard

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#164]
Dashboard for Product Manager. The Product Manager is like the admin for the platform. He can give users more permissions (proofreading and reviewer permissions), download IDML files, upload products to the website, etc.

Functions:

    Projects

Search function where the product manager can search projects by title, status and language.

List with the summary information of each project- in that list we should have the title of a project, the languages and its status(represented by colors).

When the product manager clicks on one of the languages box it should open a screen with its information(see screenshot details and details 2).

Once the "details" screen is active he should see the following information:
i. Title;
ii. Proofreader (it should also allow to unassign and assign a new one when needed);
iii. Reviewer (it should also allow to unassign and assign a new one when needed);
iv. Currently status and last date of status update (and a bar with the percentage);
v. once the "review" status reaches 100% the button "Download IDML" should be activated.

The color of the language indicated the status it is in:
i. During translation process - bar becomes red;
ii. During proofreading process- bar becomes orange;
iii. During reviewing process -bar becomes green.

    Members

Search function where the product manager can search all members registered on the platform by name, skill ,language and role.

List of members (see screenshot members) containing the information of name,role,language(if a member is assign as proofreader or reviewer the box representing this specific language should be highlighted in light orange or light green according the role). i.
i. Translator- red;
ii. Proofreader - orange;
iii. Reviewer - green.

In the right corner we should have 2 icons(more info and edit).

By clicking on "info" it should open a screen(see screenshot members info) where the product manager can access the full profile information of this specific member.

By clicking on "edit" it should open a screen(see screenshot members edit) where the product manager can select the role for the member and specifies for which language this new role should be activated.

    Checklists

The product manager should be able to add and edit the information for all the checklists(translator,proofreader,reviewer,graphic designer and product manager).

Once he clicks on one of the options (translator,proofreader,reviewer, graphic designer or product manager) a text editor should appear below allowing him to edit text of the checklist and save the changes.

Bootstrap components

https://getbootstrap.com/docs/4.0/components/modal/ (more info and edit)
https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios-1 (for select a role)

https://useiconic.com/open/ (list icon) - more information function
https://useiconic.com/open/ (cog icon) - edit function

**Comment by m-dotcom** [comment]
Do you want me to list all issue and improvements here or in separate issues?

**Comment by vibby** [comment]
In other issues please.

**Comment by m-dotcom** [comment]
Excellent, thank you!
