### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#169]
Just tested the bug report because Marisa will start taking over the function as product manager this week and make sure all products are properly uploaded and parsed. 

When a bug is reported does it go to all who are admins? Also, I see it is send from a gmail account, I guess you were the person setting it up. 

Where do emails go that are send to adventistcommons@gmail.com? Do you have access to it?

![Screen Shot 2020-04-21 at 9 58 07 AM](https://user-images.githubusercontent.com/51795720/79835095-cfb12100-83b6-11ea-9533-c507687b116a.png)

**Comment by vibby** [comment]
It is sent to all admins. For access, you got them.

**Comment by vibby** [comment]
done
