### ISSUE TITLE
Project standards

### ISSUE THREAD

**Issue by rafaelji** [AdventistCommons/adventistcommons.org#17]
I don't know if already exists, but would be great if we have project standards for the descriptions of the commits, pull requests and so on. 

I think that at least for the description of the commits to avoid hard to understand descriptions. It can have the ticket number plus a description, I don't know, it's just a suggestion. 

We could create a repository under the AdventistCommons to handle these standards. What you think?

**Comment by akjackson1** [comment]
How about using the Wiki feature in Github? Haven't used it before, but seems like it would work?

**Comment by rafaelji** [comment]
Where can I see this Github Wiki? I think that I didn't know it yet.

**Comment by rafaelji** [comment]
@akjackson1 I started writing the wiki, you can check it here: https://github.com/AdventistCommons/adventistcommons.org/wiki

I think that a better approach would be to create a new repository because we will have a tight review about what is being changed.

**Comment by akjackson1** [comment]
@rafaelji great start. I see your point about having a better review process. I've created a new repository that you can use for this: https://github.com/AdventistCommons/developer-guide

Thanks for working on this!

**Comment by rafaelji** [comment]
Ok, I will move the created page to there.
Thanks @akjackson1

**Comment by akjackson1** [comment]
Closing this since we're now managing all our tasks on [Trello](https://trello.com/invite/b/cCdSmpc0/4527547fa5dedeee84a0ccae33d08865/adventist-commons-development).
