### ISSUE TITLE
Delete Project

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#171]
When I try to delete a project under "translations" (nav bar), I receive the following page:

![Screen Shot 2020-04-21 at 10 26 49 AM](https://user-images.githubusercontent.com/51795720/79837858-c45ff480-83ba-11ea-82c6-dd4c816ddca4.png)

**Comment by m-dotcom** [comment]
After pressing the delete button, following error appeared.

<img width="731" alt="Screen Shot 2020-04-21 at 7 41 12 PM" src="https://user-images.githubusercontent.com/51795720/79890422-21ce6280-8408-11ea-9186-e631967a640d.png">

**Comment by vibby** [comment]
Fixed : it was unable to remove download log when the attachment was deleted

**Comment by m-dotcom** [comment]
Perfect. Thanks.
