### ISSUE TITLE
Enable Download of Projects after Login

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#173]
After we upload a translated PDF file of a projects, the same "login to download" button should become also available on projects. After users log in, they can download it. Right now it is only visible when you are logged in.

I think also that after the status of a project is switched to "Downloadable" the "Continue Translating/Translate" Button should be removed and only "Download" should be available. 
![Screen Shot 2020-04-21 at 10 38 54 AM](https://user-images.githubusercontent.com/51795720/79839147-c6c34e00-83bc-11ea-99c8-5494d9df962d.png)

**Comment by vibby** [comment]
Done for the login invite
For the translation button I made it available to product manager only if the status is reviewed or downloadable. In that case, the wording is «fix translation»

**Comment by m-dotcom** [comment]
Very well done.
