### ISSUE TITLE
English Projects

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#176]
Why do we have English project in this product, and all other products don't have it?

![Screen Shot 2020-04-21 at 11 24 35 AM](https://user-images.githubusercontent.com/51795720/79843286-bca44e00-83c2-11ea-8df3-addd357bb844.png)

**Comment by vibby** [comment]
No sure about this. Maybe you just created the project for that product in english ?

**Comment by m-dotcom** [comment]
You are right. I would delete it, but I can't. It's a bug that I opened an issue for so I will close this one here.
