### ISSUE TITLE
Issue with Multiple Languages in Product Search

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#178]
Do you think it makes sense of us to have all languages shown here with the product, because if we add more, the interface will not look neat. Do you think we should just show the number of languages it is available in? The rest they can see when they go to "translation" or click on the product.

![Screen Shot 2020-04-21 at 12 24 02 PM](https://user-images.githubusercontent.com/51795720/79849361-085af580-83cb-11ea-9e26-3f6dbeb90b01.png)

**Comment by vibby** [comment]
I propose to show the 5 first, and add other in number. Like this : «English, French, German, Dutch, Spanish and 11 more»

**Comment by m-dotcom** [comment]
Great idea...

**Comment by m-dotcom** [comment]
Perfect
