### ISSUE TITLE
Translation Memory and Machine Translation

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#181]
I think if you move "No Translation" underneath each section, and also add the "copy" button, then we can leave these two functions in the editor even though right now its not available yet.

![Screen Shot 2020-04-21 at 12 42 18 PM](https://user-images.githubusercontent.com/51795720/79851332-d4cd9a80-83cd-11ea-94f2-48e62b3e1653.png)
![Screen Shot 2020-04-21 at 12 42 41 PM](https://user-images.githubusercontent.com/51795720/79851224-b1a2eb00-83cd-11ea-9b5b-4f2c83f7ec8a.png)

**Comment by m-dotcom** [comment]
I prefer not hiding this section because we need to show it to several partners.

**Comment by vibby** [comment]
It’s ok Michael. Deployment in process.

**Comment by m-dotcom** [comment]
Thanks very much.
