### ISSUE TITLE
Comment Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#182]
When commenting on a specific sentence, there appears usually a "none found" sentence, and also the cursor for the comment somehow starts not at the beginning.

![Screen Shot 2020-04-21 at 12 45 41 PM](https://user-images.githubusercontent.com/51795720/79851550-22e29e00-83ce-11ea-993b-6a5eeb02a513.png)

**Comment by m-dotcom** [comment]
Seems like if I comment, the comments are not being stored and displayed.

**Comment by vibby** [comment]
Comment system is not done yet.

**Comment by m-dotcom** [comment]
Yes
