### ISSUE TITLE
Comment Icon

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#183]
It would be very helpful for the translator and proofreader if they could see with this icon where specific comments have been made (line of where the sentence with the comment begins) so they can check any important feedback left. 

https://material.io/resources/icons/?search=comment&icon=insert_comment&style=baseline

![Screen Shot 2020-04-21 at 12 57 00 PM](https://user-images.githubusercontent.com/51795720/79852731-b8caf880-83cf-11ea-9127-755c977db83e.png)

**Comment by vibby** [comment]
The comment system do not work at all for the moment. I will do that later.

**Comment by m-dotcom** [comment]
Thanks.
