### ISSUE TITLE
Restore Revisions Icon Missing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#184]
Maybe this could be used for the machine translation, translation memory, and revisions in case we don't have an icon that we can use? Let me know if something else is needed and I can search.

https://material.io/resources/icons/?search=arrow&icon=reply&style=baseline

![Screen Shot 2020-04-21 at 12 58 50 PM](https://user-images.githubusercontent.com/51795720/79853017-2b3bd880-83d0-11ea-9dbd-db1b8d71ea1d.png)

**Comment by m-dotcom** [comment]
Great. Just to be consistent, can you make the button a bit smaller, turn the arrow around (let me know and I can provide you with a changed file if needed), and make it grey (doesn't have to be white like in the below draft?

![Screen Shot 2020-04-22 at 9 56 48 AM](https://user-images.githubusercontent.com/51795720/79950384-b0ca9180-847f-11ea-91a1-61e74623cef5.png)

**Comment by vibby** [comment]
For the icons, we use https://fontawesome.com/icons?d=gallery&m=free
I tried something, let me know.

**Comment by m-dotcom** [comment]
Yes thats good enough. Thanks.
