### ISSUE TITLE
"Notify Me" Function

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#186]
I think there was a function in the below profile that said "Notify me when new products are available" if I am not mistaken.

![Screen Shot 2020-04-21 at 1 29 02 PM](https://user-images.githubusercontent.com/51795720/79855788-17927100-83d4-11ea-85a1-ab8d3b347d0d.png)

**Comment by vibby** [comment]
yes, it exists but it was only in the create account form until today.

**Comment by m-dotcom** [comment]
Super!!!
