### ISSUE TITLE
Product Card Update

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#188]
After some longer discussion with Marisa today decided that we need to make a few small adjustments. This will be the last time for now, hopefully.

1. Change "Languages" to "Availability"
2. Add product page numbers with the icon https://fontawesome.com/icons/book-open?style=solid It become clear that we will need these since some early testers were confused.
3. Change the display of the "publisher link" by removing "Publisher:", removing the grey background box, and making the link _regular_ and not _bold_.

![45ddf461-1555-4904-98e6-3eeb1f6ebdbf](https://user-images.githubusercontent.com/51795720/79889805-35c59480-8407-11ea-9d62-79394d510f97.jpg)

**Comment by m-dotcom** [comment]
Can you remove "bold" and the grey background?

![Screen Shot 2020-04-22 at 12 30 55 PM](https://user-images.githubusercontent.com/51795720/79965803-28ef8200-8495-11ea-89cb-26a2170fb546.png)

Also, did you add something blue? I think right now we just add it manually to the picture cover and we can deal with it later if we want to make it automated from the platform.

![Screen Shot 2020-04-22 at 12 31 36 PM](https://user-images.githubusercontent.com/51795720/79965901-4c1a3180-8495-11ea-9118-d44ca2256ccc.png)

**Comment by m-dotcom** [comment]
If you now make the font size of the publisher link the same size as the text that lists the languages we are ready to go :-)

**Comment by vibby** [comment]
For the blue label, it works just fine now, no need to add it in the image

For the publisher, I fixed the size. Please note it cannot be blue if there are no link. User have to know it’s link by the color.

**Comment by m-dotcom** [comment]
Publisher link doesn't seem to be on the same level now as the rest of the text.

![Screen Shot 2020-04-22 at 2 32 36 PM](https://user-images.githubusercontent.com/51795720/79977060-50027f80-84a6-11ea-8ead-1bc5436b6428.png)

**Comment by vibby** [comment]
I think I do dirty stuff here. Please keep in mind that styling must be redone some day, by a better frontend dev :/

**Comment by m-dotcom** [comment]
Thanks for doing it, despite being backend developer..
