### ISSUE TITLE
Proofreader Dashboard

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#189]
Could it be that the proofreader@ account has reviewer permissions? Somehow it shows the reviewer dashboard. I couldn't find where to change the permissions otherwise I would have looked into it.

**Comment by vibby** [comment]
What does make you think that ?

**Comment by m-dotcom** [comment]
When proofreader is logged in, the review section is shown...Also says he is reviewer and not proofreader.

![Screen Shot 2020-04-22 at 11 41 52 AM](https://user-images.githubusercontent.com/51795720/79960659-54bb3980-848e-11ea-8f18-7587f8f380f0.png)

**Comment by vibby** [comment]
Right. Thank you for the catch

**Comment by m-dotcom** [comment]
Problem persists. Also, column on right page of website shows up somehow now.

![Screen Shot 2020-04-22 at 2 30 51 PM](https://user-images.githubusercontent.com/51795720/79976828-ec785200-84a5-11ea-8856-39c2590884a8.png)

**Comment by vibby** [comment]
I looked on the develop environment, the user «proofreader@adventistcommons.org» was a reviewer for german. I removed that with interface (as admin) and it seems ok now.

**Comment by m-dotcom** [comment]
Ok thanks.
