### ISSUE TITLE
Product Specification Update

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#191]
In the "specifications" area for each product, some words are not capitalized at the beginning even though we stored them in the database like that. See below:

1. Mark Finely
2. Adventist World Radio
3. Saddle Stitch

![Screen Shot 2020-04-22 at 9 40 46 AM](https://user-images.githubusercontent.com/51795720/79948920-61836180-847d-11ea-9dbe-54193b55c065.png)

**Comment by m-dotcom** [comment]
Seems like still needed for some:

![Screen Shot 2020-04-22 at 11 40 18 AM](https://user-images.githubusercontent.com/51795720/79960490-1faee700-848e-11ea-9b57-39b4b45f2b25.png)

**Comment by m-dotcom** [comment]
Same problem persists.

![Screen Shot 2020-04-22 at 12 33 39 PM](https://user-images.githubusercontent.com/51795720/79966148-a9ae7e00-8495-11ea-9043-bc4a1ab1f439.png)

**Comment by vibby** [comment]
ooups

**Comment by m-dotcom** [comment]
Issue persists. 

![Screen Shot 2020-04-22 at 1 32 38 PM](https://user-images.githubusercontent.com/51795720/79971915-c2bb2d00-849d-11ea-8942-2c7c430c4529.png)

**Comment by vibby** [comment]
I had an error at git push I did not notice :/

**Comment by m-dotcom** [comment]
Perfect
