### ISSUE TITLE
Page Number Icon

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#195]
This is not a bug, but a visual suggestion: Could the icon of page number be in a softer color, like #c8c8c8? Thanks!
--

![Screen Shot 2020-04-22 at 4 22 54 PM](https://user-images.githubusercontent.com/51795720/79987031-94494c00-84b5-11ea-92cd-bf464b7fd0b8.png)

**Comment by m-dotcom** [comment]
I will try to see if we can find a front-end person to help us.

**Comment by vibby** [comment]
I do that in a quick and dirty way

**Comment by m-dotcom** [comment]
Great.
