### ISSUE TITLE
Admin Feedback 

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#198]
Is this file https://github.com/AdventistCommons/adventistcommons.org/blob/develop/templates/email/admin/feedback.txt.twig

still needed, since we have

https://github.com/AdventistCommons/adventistcommons.org/blob/develop/templates/email/admin/feedback.html.twig

**Comment by vibby** [comment]
Yes they are both used, we send both formats. So email clients can choose which they want.
You can see that here : https://github.com/AdventistCommons/adventistcommons.org/blob/develop/src/Email/SenderToAdmin.php#L41

**Comment by m-dotcom** [comment]
Okay. I didn't know that is possible. Thanks.
