### ISSUE TITLE
Website Unavailable at Times

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#204]
At times the website doesn't work. Then it works in Chrome but not Safari. Any thoughts?

![237f2151-87d5-4722-909e-53893c272abf](https://user-images.githubusercontent.com/51795720/79996479-2efb5800-84c1-11ea-9488-4993e80dc909.jpg)

**Comment by vibby** [comment]
It must be the DNS problem

**Comment by m-dotcom** [comment]
Ok, for now we don't worry about it. Thanks.
