### ISSUE TITLE
Product Search Page Filters

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#206]
It appears that the below filtering elements are not working on the product search page

![Screen Shot 2020-04-23 at 8 11 45 AM](https://user-images.githubusercontent.com/51795720/80061553-43c80200-853a-11ea-8f0a-753bb54b1a49.png)

**Comment by vibby** [comment]
It seems ok to me.
![image](https://user-images.githubusercontent.com/1181902/80076397-711dab80-854c-11ea-8f7e-3d68cb28b1fa.png)
Maybe you clicked on «view all» which means «remove all filters». We may need to change color or wording of the «reset» button ?

**Comment by m-dotcom** [comment]
You are right. Shall we do like this?

![Screen Shot 2020-04-23 at 11 43 02 AM](https://user-images.githubusercontent.com/51795720/80078450-9fed4f00-8557-11ea-9ee3-acea78f18b1f.png)

**Comment by m-dotcom** [comment]
Perfect
