### ISSUE TITLE
Spelling of Skills

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#207]
Where am I able to change the spelling of these?

![Screen Shot 2020-04-23 at 9 38 27 AM](https://user-images.githubusercontent.com/51795720/80070865-59462780-854c-11ea-9fcc-43a5492444df.png)

**Comment by vibby** [comment]
You can manage them in the admin interface http://develop.adventistcommons.org/admin

**Comment by m-dotcom** [comment]
Thanks.
