### ISSUE TITLE
Missing Languages in Admin Area

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#208]
When I try to approve a user for a specific language for proofreading and review in the Admin area, not all languages are displayed.

![Screen Shot 2020-04-23 at 11 30 31 AM](https://user-images.githubusercontent.com/51795720/80078651-e2af2700-8557-11ea-9871-1525c311c500.png)

**Comment by vibby** [comment]
Please, do that in the members section of product manager dashboard :)
I will look for that later

**Comment by vibby** [comment]
It’s ok actually. The list only show the first items, but you can type another language, it will be proposed.
This is done to handle very long lists, like thousands of members.

**Comment by m-dotcom** [comment]
Thanks.
