### ISSUE TITLE
Portuguese Language

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#209]
Marisa has been translating to Portuguese and said we need to add the Portuguese (Brazil) also. 

This is how we list languages

Language...Code...Google Code....

Here you can find the Portuguese Brazil Google Code pt-BR, but I am not sure where to find the other 3 letter code. 

https://developers.google.com/admin-sdk/directory/v1/languages

![Screen Shot 2020-04-23 at 11 28 51 AM](https://user-images.githubusercontent.com/51795720/80078820-1722e300-8558-11ea-86d8-1f1570ed43a0.png)

**Comment by vibby** [comment]
This code is a free string. It is used on website do identify a language or a project (which use the product slug and the language code). You can use any 3 chars string you want ! Maybe ```ptb``` is a good choice for Brazilian Portuguese.

**Comment by m-dotcom** [comment]
Perfect.
