### ISSUE TITLE
Add "Illustration (digital art)" to skills

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#21]
In the second step of the sign up process users are asked to select their skills. We are missing the option for "Illustration (digital art)". 

<img width="615" alt="Screen Shot 2019-07-01 at 11 26 59 AM" src="https://user-images.githubusercontent.com/51795720/60448432-90c99900-9bf3-11e9-8ed9-b7d5b409812a.png">

**Comment by akjackson1** [comment]
Closing this since we're now managing all our tasks on [Trello](https://trello.com/invite/b/cCdSmpc0/4527547fa5dedeee84a0ccae33d08865/adventist-commons-development).
