### ISSUE TITLE
Delete Unstarted Projects

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#210]
When I start a new project but do not go inside the editor to make a translation, the project is not listed under the "translation" page in nav bar and cannot be deleted. I think it would be good to list it there, even though we don't have a translation yet. This way we can remove it if needed. 

![Screen Shot 2020-04-23 at 11 17 00 AM](https://user-images.githubusercontent.com/51795720/80079336-d2e41280-8558-11ea-995d-55d174118153.png)

**Comment by vibby** [comment]
What about add a delete button in language line, for product managers, in the product show page you show above ?

**Comment by m-dotcom** [comment]
Ok, that is fine.

**Comment by vibby** [comment]
yes

**Comment by m-dotcom** [comment]
Works perfect, Vincent. Excellent.
