### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#211]
Repeatedly tried to delete account with name "testing" but get this error.

![Screen Shot 2020-04-23 at 12 01 11 PM](https://user-images.githubusercontent.com/51795720/80080342-273bc200-855a-11ea-8b43-706e87915486.png)

**Comment by vibby** [comment]
Hum, an account will never be deleted, but it can be anonymized, which means remove all identify data.
A user can do it with his own account. But the admin can not do it.
I should just remove that delete button.

**Comment by m-dotcom** [comment]
Ok, but we had soo many test accounts that I removed which we don't use anymore.

**Comment by vibby** [comment]
I found a solution to delete users. It may breaks some stuff if he did some translation : translator is set to null if so.

**Comment by m-dotcom** [comment]
Ok, I will not use this delete anymore from now on, unless to test something specific on a test product and need to delete user or so... but probably never again.
