### ISSUE TITLE
AC Logo Missing

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#215]
It appears that the logo in the account confirmation email is not showing up.

![c0109fde-de82-40d6-9916-c1abf8f6ebb4](https://user-images.githubusercontent.com/51795720/80090692-8f91a000-8568-11ea-9894-2957915d912b.jpg)

**Comment by vibby** [comment]
It works for me. 
![image](https://user-images.githubusercontent.com/1181902/80092584-4db22b00-8563-11ea-9d5f-45c372fc85bb.png)
The url seems ok. Maybe she has to allow foreign to be shown if her email client ?

**Comment by m-dotcom** [comment]
Strange... will check again.
