### ISSUE TITLE
Update Text

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#216]
Where would I be able to update the below text?

![c0109fde-de82-40d6-9916-c1abf8f6ebb4](https://user-images.githubusercontent.com/51795720/80090804-bd76e480-8568-11ea-8cff-482b981a3bcc.jpg)

**Comment by vibby** [comment]
It’s her for the moment : https://github.com/AdventistCommons/adventistcommons.org/blob/develop/src/Email/SenderToUser.php#L38
The emails contents are not translated.

**Comment by m-dotcom** [comment]
Thanks. Just making sure all the text is correct everywhere.
