### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#218]
It appears that the profile picture doesn't change, even if account with Gravatar was created. Maybe better to allow upload of a pic? What are your thoughts?

![Screen Shot 2020-04-23 at 2 42 37 PM](https://user-images.githubusercontent.com/51795720/80095506-b5bb3e00-8570-11ea-870e-6311890cff66.png)

**Comment by m-dotcom** [comment]
Will check again

**Comment by m-dotcom** [comment]
It worked now, but you have to signup to Wordpress, and upload a pic, and giver manual permission by entering the URL to get your profile picture working. In my opinion nobody wants to do that so complicated. What do you think?

**Comment by vibby** [comment]
Personaly, I think gravatar is just perfect from many points of view. It does not requires any development, nor any maintenance effort. The more code we write, the errors we make !

**Comment by m-dotcom** [comment]
Ok, in that case I will add some more information on how to change it so user can know how to do it.
