### ISSUE TITLE
Display Username

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#219]
I think this is Warlen's Account but I can't confirm since his name is not showing.

![Screen Shot 2020-04-23 at 2 54 42 PM](https://user-images.githubusercontent.com/51795720/80096551-70980b80-8572-11ea-9a6c-85c7fac84050.png)

**Comment by vibby** [comment]
I found why this is happening : she created her account but never validated her email. What should I do then ? Can a user connect even if he did not validate his email ?

**Comment by m-dotcom** [comment]
No, a user should only be able to login if he has validated his email address.

**Comment by vibby** [comment]
The issue is fixed in the way, users that are not active cannot login, so they cannot translate anything.

**Comment by m-dotcom** [comment]
Perfect
