### ISSUE TITLE
Product Card Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#225]
Seems like if we have a long title we run into this issue again:

![Screen Shot 2020-04-23 at 5 21 54 PM](https://user-images.githubusercontent.com/51795720/80110201-181f3900-8587-11ea-84d1-c560325fb44e.png)

Do you think it makes sense to do something like this:

![Screen Shot 2020-04-23 at 5 36 21 PM](https://user-images.githubusercontent.com/51795720/80114997-e610d580-858c-11ea-87d1-d67bab5ea5cc.png)

Just want to know what you think.

**Comment by vibby** [comment]
Do you propose to put all cards on full width ? or only those with long names ?

**Comment by m-dotcom** [comment]
I was thinking all cards on full width, but want to first hear what you think?

**Comment by vibby** [comment]
I don’t know … That makes longer pages … why not ?

**Comment by m-dotcom** [comment]
Ok lets do it. Hope its not much work for you...

**Comment by vibby** [comment]
This task is *very* short :)

**Comment by vibby** [comment]
@m-dotcom : I created the milestone Beta «20.04» I propose a versionning system in ubuntu style 20 for 2020 and 04 for april. Please, assign this milestone for any report that applies for the beta version.

**Comment by m-dotcom** [comment]
Ok Thanks.
