### ISSUE TITLE
User Account

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#232]
Did you set up this account?

![Screen Shot 2020-04-25 at 7 33 39 PM](https://user-images.githubusercontent.com/51795720/80285215-04f99e00-872c-11ea-9198-f5b138d7e00d.png)

**Comment by vibby** [comment]
No, that is not me …

**Comment by m-dotcom** [comment]
Somehow people find already the website... its fine I hope
