### ISSUE TITLE
Members Search Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#233]
It seems that the members search in Product Manager Dashboard is not working.

![Screen Shot 2020-04-25 at 7 32 24 PM](https://user-images.githubusercontent.com/51795720/80285231-222e6c80-872c-11ea-867d-ff6d4b8c6d49.png)

**Comment by vibby** [comment]
It works, but it search on last name only. Do you want me to search in first name too ? or change label to make it clearer ?

**Comment by m-dotcom** [comment]
If it can be able to search for first name and last name it would be great.

**Comment by m-dotcom** [comment]
Works perfectly! Great job.
