### ISSUE TITLE
Translation Page - Display Progress

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#234]
Seems like in the "translation" site in nav bar the progress for each project is not showing up.

![Screen Shot 2020-04-25 at 7 40 22 PM](https://user-images.githubusercontent.com/51795720/80285319-a680ef80-872c-11ea-9a6b-94dd4226480e.png)

**Comment by vibby** [comment]
Done. Please note that this makes the page to perform 229 sql queries. which means we will have to optimize that for production.

**Comment by m-dotcom** [comment]
Wow, that is great that it can show this. I was actually talking about the tracking below, but I also like that it can show the progress with a bar. Great job!

![Screen Shot 2020-04-26 at 7 42 42 AM](https://user-images.githubusercontent.com/51795720/80298081-a2d38400-8791-11ea-9c9c-d5475d54403a.png)

**Comment by vibby** [comment]
It’s the number of element reviewed, not only translated. Are you sure it is a good idea to show translated count ? We will have the problem on the other side : it can show up 72/72 as if it is finished but not any reviewed or proofread … What do you think ?

**Comment by m-dotcom** [comment]
I think we should show the translation progress there like we do it on the project pages. If it is in proofreading or review there can see the status on the bottom right.

**Comment by m-dotcom** [comment]
Perfect job, as usual.
