### ISSUE TITLE
Download IDML Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#235]
When I try to download the Original IDML for this project, I get put into a empty page loop.

It seemed to work on another project though. 

![Screen Shot 2020-04-25 at 7 42 38 PM](https://user-images.githubusercontent.com/51795720/80285351-ef38a880-872c-11ea-9d5a-3431eb6f17d3.png)

**Comment by vibby** [comment]
That was because of the long download path, due to a long name

**Comment by m-dotcom** [comment]
Perfect
