### ISSUE TITLE
RTL Languages

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#236]
Do you think we should make all RTL languages unavailable for now because we don't support them right now?

**Comment by vibby** [comment]
Let me just do a test of it …

**Comment by vibby** [comment]
Seems not bad. please give it a try by someone able to manage it.

**Comment by m-dotcom** [comment]
Working on that...

**Comment by m-dotcom** [comment]
Had an Arabic translator do some work on it and seemed to be working fine.
