### ISSUE TITLE
Proofreading Alert

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#237]
You did a great job with the platform!

I have a suggestion that would be very helpful. Right now when a proofreader starts proofreading a project for the first time, there is no message that tells him that he will be assigned exculsively to this project and that if he can't continue he has to unassigned himself. It would be good to have a message like this I think.

**Comment by vibby** [comment]
ok. How would you feel that ? a popin when he validates his first proofread ? Or a banner that always stay on top of the translation board ?

**Comment by m-dotcom** [comment]
I think a banner would probably be better so they understand that. Lets try that.

**Comment by m-dotcom** [comment]
Works perfectly.
