### ISSUE TITLE
Proofreading Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#238]
When the proofreader approves the sentences but notices that there is a mistake, he clicks on "translate" again in order to correct the sentence, and then approve it. 

However, when I do this I get an error. 

![Screen Shot 2020-04-25 at 8 17 26 PM](https://user-images.githubusercontent.com/51795720/80286053-ccf55980-8731-11ea-95d9-f1e9bf2d4e5a.png)

Seems translation is locked when the proofreader is proofreading, but he may need to change sentences at times. Anyone should be always able to submit translations, but as soon as a sentence is proofread, that sentence is the one that is been used, and any other translation from users is only a further revision. 

That is important because if users make a bad translation, the proofreader needs to be able to fix it.

**Comment by vibby** [comment]
I cannot reproduce that even on develop.adventistcommons.org
Here are my steps :
- Connect as a product manager
- Create a new translation on an existing product
- Enter editor for first section
- Enter a translation for first sentence
- Hit enter to save it
- Click back on that sentence
- Switch to proofreader in translation working area
- Click on «approve» button. It works

What I saw as an error : when I try to click on the «approve» button when sentence is not translated yet. Is that what you were talking about ? what should happen then ?

**Comment by m-dotcom** [comment]
OK, I will close this for now and redo the testing again. If needed I will open this issue.
