### ISSUE TITLE
Progress Counting

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#239]
I made a product called "testing2," just to try all kinds of different scenarios of what users can make wrong... somehow in one of the section the tracking went wrong:

![Screen Shot 2020-04-25 at 8 30 10 PM](https://user-images.githubusercontent.com/51795720/80286386-ca93ff00-8733-11ea-8384-2ae455572e73.png)

**Comment by vibby** [comment]
Oups. I am so sorry. I saw that product on develop.ac.org and I tought that is a test I did myself. So I removed it :$ Can you please recreate it ? :confused:

**Comment by m-dotcom** [comment]
No problem. I will create a product for further testing today and see if the error comes up again!
