### ISSUE TITLE
Proofreader Dashboard

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#241]
When the translator is finished with all the text in a project, right now nothing happens because the proofreader has to assign himself. But how does the proofreader know that he can assign himself. Of course, later it will be by notification as soon as a project has 100% text translated, but we should show also in his dashboard here (this is proofreader dashboard):

![Screen Shot 2020-04-26 at 8 16 47 AM](https://user-images.githubusercontent.com/51795720/80298605-ca791b00-8796-11ea-8604-c96dd685ec83.png)

Here the proofreader can assign himself and unassigns himself. Of course, in the translation project section, they will see the products that are available for translation, as we have it right now. This is correct. I will do some changes to the texts later to make it clearer. 

![Screen Shot 2020-04-26 at 8 16 24 AM](https://user-images.githubusercontent.com/51795720/80298622-f09ebb00-8796-11ea-8a41-94a611119c5a.png)

**Comment by vibby** [comment]
Done. But I think it is very limitative to show only project that have translations finished. MAy they can start proofread even if it is done finished yet ?

**Comment by m-dotcom** [comment]
Yes he can, but lets only list those who are finished with translation to focus on those. The banner is great, I think later we have to give a email notification that the person was assigned to the project. 

Or do you think we should make a popup to ask if the person wants to assign himself to proofread it, AND also show the banner? Because otherwise maybe he is not aware.

**Comment by vibby** [comment]
Anyway, this is very unclear, when he proofread something, he becomes the only proofreader …

**Comment by m-dotcom** [comment]
Ok, lets allow him to assign himself to any project, even if translation is not finished, until he unassigns himself. Also, like you suggest, make the popping to let him know that he became the proofreader, plus show the banner.

**Comment by m-dotcom** [comment]
I think this is done. If we need to fix something else on it I will open another ticket.
