### ISSUE TITLE
Proofreading Issue

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#242]
I am testing right now with this product: http://develop.adventistcommons.org/en/products/the-silent-killer/project/ger

Gave the proofreader permission to proofread German, but when I enter the account I am unable to switch to proofreading in editor. 

![Screen Shot 2020-04-26 at 8 23 41 AM](https://user-images.githubusercontent.com/51795720/80298686-86d2e100-8797-11ea-8bc7-ce0049534660.png)

**Comment by vibby** [comment]
It is already being proofread by another user : reviewer@adventistcommons.org

**Comment by m-dotcom** [comment]
Makes sense.
