### ISSUE TITLE
Proofreading with Admin or Product Manager Account

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#244]
I was doing some proofreading with Admin account for testing because the proofreading account didn't allow me to do that. The problem is that I cannot unassigns myself from the project since this option doesn't exist in the Admin or Product Manager Account. I would like to unassigns so another proofreader can assign. 

![Screen Shot 2020-04-26 at 8 30 19 AM](https://user-images.githubusercontent.com/51795720/80298760-3f992000-8798-11ea-899a-005e4dc694af.png)

**Comment by vibby** [comment]
Many ways to manage this.
- You should be able to unassign yourself in the projects view of product manager, for both reviewer and/or proofreader ?
- You should see the project list for proofreader as a product manager ?
- Or, as a product manager, you should never be assigned when you proofread or review something ?

**Comment by m-dotcom** [comment]
I think that should be fine for now. Thanks!
