### ISSUE TITLE
Signup Question

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#245]
Do you think it makes sense to remove sign-up from front-page? They can do that on login page or not?

![Screen Shot 2020-04-26 at 8 45 47 AM](https://user-images.githubusercontent.com/51795720/80299434-ff886c00-879c-11ea-978b-b5f9d4bf1ef8.png)

**Comment by vibby** [comment]
I do not mind it. done

**Comment by m-dotcom** [comment]
He probably wants to download something and is automatically forced to login page. If he doesn't have an account he has to create one. It is up to you, whatever you think is best you can choose.

**Comment by vibby** [comment]
May we can change the wording of the login button, to something more generic like «identify myself» ? Can you a find a wording that match the two goals ?

**Comment by m-dotcom** [comment]
That will be very hard. In that case maybe just leave it.
