### ISSUE TITLE
Storing of Comments

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#246]
It seems that when I make a comment for a specific sentence, that comment is also stored for the next sentence in that paragraph, could that be?

**Comment by vibby** [comment]
That does not happens to me on my env, nor on develop.ac.org 
Can you be more precise in steps to reproduce please ?

**Comment by m-dotcom** [comment]
Can't reproduce it either now. Will close this and if I notice it again try to pay better attention.
