### ISSUE TITLE
Comment Icon

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#247]
Were you not able to use the "insert_comment" icon?

https://material.io/resources/icons/?search=comment&icon=insert_comment&style=baseline

The little arrow on the bottom of the bubble right now also points in the wrong direction. See below:

![Screen Shot 2020-04-26 at 12 33 02 PM](https://user-images.githubusercontent.com/51795720/80303636-17221d80-87ba-11ea-9d53-2061542086a6.png)

**Comment by vibby** [comment]
We do not use material.io, but [fontawesome free set](https://fontawesome.com/icons?d=gallery&m=free). Can you find a better icon here ? Maybe this : https://fontawesome.com/icons/comment-dots?style=solid ?

**Comment by m-dotcom** [comment]
Looks good https://fontawesome.com/icons/comment-dots?style=solid

**Comment by m-dotcom** [comment]
Great
