### ISSUE TITLE
Publisher Link Target

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#248]
Can you have all the publishers links that are displayed on each product open in a new window? Its a small thing I know :-)

**Comment by vibby** [comment]
Done. But please not this a very controversial practice. Read for example https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by m-dotcom** [comment]
I didn't know that. If you want you can revert it back, its fine with me. You decide.

**Comment by vibby** [comment]
I propose to keep current window link, with an icon to tell users they will get out of the current website.

**Comment by m-dotcom** [comment]
Perfect
