### ISSUE TITLE
Use of Revisions

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#252]
I am trying to use an earlier revision, but it is giving me issues doing that. 

If I use the latest revision I can restore it, but the other ones it is giving me errors. 

![Screen Shot 2020-04-26 at 3 32 47 PM](https://user-images.githubusercontent.com/51795720/80307676-37120b00-87d3-11ea-8449-a3d4de0324e3.png)

**Comment by vibby** [comment]
I cannot reproduce exactly the error you said, but that make me discover a bug : the revisions history was showing all projects revision for sentence (all languages). I fixed it. Can you try it back ?

**Comment by m-dotcom** [comment]
Seems to work now. Thank you.
