### ISSUE TITLE
Show Projects to Review

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#255]
I have a project in German that is ready for review. The reviewer account is approved to review German but it doesn't show that in the available projects. Whatever permission we give for the person to review project should show there.

![Screen Shot 2020-04-26 at 4 01 03 PM](https://user-images.githubusercontent.com/51795720/80308360-3da28180-87d7-11ea-8adc-b87897a3bf6d.png)

**Comment by vibby** [comment]
This happens because there is already someone else reviewer for that project

**Comment by m-dotcom** [comment]
Ok thanks. I thought I checked and nobody was there but was my mistake. Thanks
