### ISSUE TITLE
Review Function in Editor

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#256]
I am signed in with the reviewer account and it assigned me but I cannot switch to "review"

![Screen Shot 2020-04-26 at 4 05 48 PM](https://user-images.githubusercontent.com/51795720/80308491-113b3500-87d8-11ea-978c-d2f9b9eec63f.png)

**Comment by vibby** [comment]
This happens because the project in not anymore in the status «translated». It is completly proofread. So it reached the status «proofread». To you want to keep it visible even you cannot do anything ?

**Comment by m-dotcom** [comment]
Why we cannot do anything now? Now the reviewer should be able to review everything on the project and be able to approve the proofreading, change a translation if he needs to, and make sure all is perfect.

**Comment by m-dotcom** [comment]
Great.
