### ISSUE TITLE
Show Projects under Review

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#257]
I am assigned to the project to review:

![Screen Shot 2020-04-26 at 4 05 48 PM](https://user-images.githubusercontent.com/51795720/80308538-49db0e80-87d8-11ea-9516-55e18159d974.png)

But cannot find it in the dashboard:

![Screen Shot 2020-04-26 at 4 06 58 PM](https://user-images.githubusercontent.com/51795720/80308550-5495a380-87d8-11ea-97d3-df73805ad580.png)

**Comment by vibby** [comment]
Same answer as https://github.com/AdventistCommons/adventistcommons.org/issues/256
We only show products in the status of being proofread (which we call «translated»)

**Comment by vibby** [comment]
I fixed that issue : show review even if a proofreader is assigned and differs form current user. But I have a question : do we change the proofreader if the reviewer change a translation and proofread it ?

**Comment by m-dotcom** [comment]
No, if the reviewer change, translation, proofread it, and review it, it is fixed and completed. No more proofreading from different user needs to be done. That person has final authority.

**Comment by m-dotcom** [comment]
Great Thanks.
