### ISSUE TITLE
Proofreading Unassign Error

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#260]
Trying to unassigns myself from the project with reviewer account but its not working.

<img width="1172" alt="Screen Shot 2020-04-26 at 6 46 37 PM" src="https://user-images.githubusercontent.com/51795720/80312544-62562380-87ee-11ea-84ff-c96c96daef46.png">

**Comment by vibby** [comment]
I understand what happen here. We do not only show project that the user is proofreader or reviewer, but all projects that the user has ever review or proofread in the past. I propose this : We keep those lines, but we remove the button «unassign» on those. What do you think about that ?

**Comment by m-dotcom** [comment]
If the reviewer is not assigned anymore but has contributed in the past, this project should be shown in the "Reviews" history area. In "currently reviewed by me" only those that are active and he is assigned to.

**Comment by m-dotcom** [comment]
I am closing this now and will open a issue if we have a problem again, based on the new rules we made.
