### ISSUE TITLE
RTL for Comments and Revisions

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#261]
Comments and Revisions should also be RTL for RTL languages.

<img width="587" alt="Screen Shot 2020-04-27 at 10 09 49 AM" src="https://user-images.githubusercontent.com/51795720/80344077-ac331e00-886f-11ea-9107-23c75fa3978f.png">

**Comment by vibby** [comment]
Done for history, but for comments, can we be sure the comments are in the target language or the source language ? not sure …

**Comment by m-dotcom** [comment]
Perfect. Lets leave it like that. They can comment in English.
