### ISSUE TITLE
Prevent Translation Changes

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#262]
When a proofreader and reviewer has started to do their work, I have noticed that a translator can still come in and change the translation. That should not be allowed.

**Comment by vibby** [comment]
We need to define those rules together once for all, then I implement them and it will be ok !

**Comment by m-dotcom** [comment]
Ok, lets define these first. Try not to work on another tasks related to this for now until we have wiki page done.

**Comment by vibby** [comment]
I think I have added all rules I am thinking about. Can you validate all of them ?

**Comment by m-dotcom** [comment]
I reviewed all the rules and added a page called "Translation Process". Please read that to make sure it is matching with site rules. 

Sorry, but I didn't know how to connect the links to the pages.

**Comment by vibby** [comment]
Ok I think we have all we need. I already updated the project status to add steps.
Now I fix all rule one by one. Can you please validate they all seem ok to you ?

**Comment by m-dotcom** [comment]
Wow, you did an amazing work. Looks fine to be except:

Rule 26 needs updating I believe:

A project switch to status «PROOFREADING» WHEN status is «REVIEWING» AND one translation it proofread -> ..status is "Proofreadable" AND...

**Comment by m-dotcom** [comment]
Thanks. Reviewing now and other translators cannot transfer while I review. This is great.
