### ISSUE TITLE
Removal of Project

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#265]
When a project is removed and re-created, it seems that the revisions somehow stay in tact. Will this not lead to problems later if we make big changes to the IDML after deleting a project, or integrate translation memory?

![aa85941b-364e-4b6e-adee-8b185e9053ad](https://user-images.githubusercontent.com/51795720/80351460-071e4280-887b-11ea-8e33-e575a37601bc.jpg)

**Comment by vibby** [comment]
I cannot reproduce this and I really think that can not happen. Here is steps I did :
- Create a project
- Translate all content
- Proofread half of them
- Delete the project
- Create anew project for the same language
- Revisions history is empty for all sentences

**Comment by m-dotcom** [comment]
Interesting. If something happens again I will open new ticket. Thanks for looking inside of it.
