### ISSUE TITLE
Project PDF Questions

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#266]
1. Why are there two "PDF (Personal)" options?
2. Are we able to remove these PDF's somehow?

Thanks

<img width="933" alt="Screen Shot 2020-04-27 at 11 16 57 AM" src="https://user-images.githubusercontent.com/51795720/80351690-7005ba80-887b-11ea-8155-6a2e9b6d794b.png">

**Comment by vibby** [comment]
1 : because you uploaded 2 file with that type
2 : not at the moment, I did not see any screen where it is possible

**Comment by m-dotcom** [comment]
Ok, we can look at this later. Not priority now.
