### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#267]
When users do something in the editor that they don't have permission to, it usually gives an error messages that says something like: "error on the server...". Are these messages customizable for different errors?

**Comment by vibby** [comment]
That is why we should not have done that in javascript :P
I tried something with 3b0dfe51e65c3dc7365b5ebcba8f2ad415c1e75b. Let me know if there are cases I did not cover.

**Comment by m-dotcom** [comment]
Thanks Vincent. I will check all the error messages and if there is a problem or one missing, open a ticket.
