### ISSUE TITLE
Sort and give priority to issues

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#270]
Hello @m-dotcom 
I propose the use of github projects system, to be able to order and give a good view on issues : https://github.com/AdventistCommons/adventistcommons.org/projects/2?add_cards_query=is%3Aopen

Can you please move issues in colons, and put them in the order in the column according to your priority, the higher is the highest priority.

May for long work, I should give you an idea of the effort to succeed it. That may will change you priority order ?

**Comment by m-dotcom** [comment]
OK will do that. Wow, didn't know you can do that. I think priority is fine.
