### ISSUE TITLE
Status Not Updating

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#277]
Translation is 100% complete, but not switching to the next status for this project. 

<img width="961" alt="Screen Shot 2020-04-28 at 3 26 59 PM" src="https://user-images.githubusercontent.com/51795720/80487030-d31f4c00-8964-11ea-8d54-27993566cc7a.png">

**Comment by m-dotcom** [comment]
Mmm.... translated again the entire text, and completed it. Status still says "Translation in Progress"

![Screen Shot 2020-04-28 at 4 54 41 PM](https://user-images.githubusercontent.com/51795720/80495752-fd770680-8970-11ea-8c83-d421c2bcd0cd.png)

**Comment by m-dotcom** [comment]
It is strange, now it shows the status correctly and deleted the last section?

![Screen Shot 2020-04-28 at 5 01 54 PM](https://user-images.githubusercontent.com/51795720/80496544-03211c00-8972-11ea-8e7a-ab89bbbb0c6c.png)

**Comment by vibby** [comment]
It was happening because the newly added translation was not taken into account. adding a new version of it made it work. Should be ok now.

**Comment by m-dotcom** [comment]
Great, thank you!
