### ISSUE TITLE
Translation Randomly Deleting

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#278]
I had 100% translation completed, starting proofreading, and then later came back to the project. Take a look, translation were missing, but reviews were there. Very strange.

![Screen Shot 2020-04-28 at 5 34 35 PM](https://user-images.githubusercontent.com/51795720/80500240-9ceac800-8976-11ea-8534-011a47fdf80f.png)

**Comment by vibby** [comment]
That is because of me :) I removed last one to make tests because of ticket #277

**Comment by m-dotcom** [comment]
But it is the first one missing :$

**Comment by vibby** [comment]
Hum … maybe not so

**Comment by m-dotcom** [comment]
Now some of the text gone... 

![Screen Shot 2020-04-28 at 5 34 35 PM](https://user-images.githubusercontent.com/51795720/80501028-9c9efc80-8977-11ea-87ce-3219683cae44.png)

**Comment by vibby** [comment]
Caught it. it was a collision between many projects on the same product.

**Comment by m-dotcom** [comment]
Yes, she was, and lost that also :)

**Comment by m-dotcom** [comment]
Great, seems like it is working now.
