### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by m-dotcom** [AdventistCommons/adventistcommons.org#281]
We are trying to make things as simple as possible in the dashboard for the beta and then going public. 

Is it possible the "password change" and the "delete my account" function inside the "profile" page?

![Screen Shot 2020-04-29 at 8 12 34 AM](https://user-images.githubusercontent.com/51795720/80562810-859cf080-89f1-11ea-9fe0-5f69a9c610f5.png)

**Comment by vibby** [comment]
That is possible, but with different submit buttons for different parts of it, that may become unclear but possible. Is that ok ?

**Comment by m-dotcom** [comment]
Better not have it unclear. I will open three different issues that will make the dashboard and user area simpler to understand for beta, and so we can focus first on what is most important. Thanks again.
