### ISSUE TITLE
Install Twig

### ISSUE THREAD

**Issue by akjackson1** [AdventistCommons/adventistcommons.org#3]
- [ ] Setup Twig using Composer
- [ ] Convert all current html views to twig templates

This isn't urgent, but would make development quite a bit easier if someone has time to tackle it!

Directions may be helpful: http://acmeextension.com/integrate-twig-with-codeigniter/

**Comment by Deadpikle** [comment]
How are you deploying the code to the server? If you're using FTP/other, wouldn't using Composer locally work anyway as long as the script/etc. was configured to upload the `vendor` folder and Composer files? It's a bit more of a pain, but keeps us from having to commit the Twig library things to the repo.

**Comment by akjackson1** [comment]
@Deadpikle my current deploy process is using DeployHQ which takes the latest commits from the repo and applies them to the server, which is extremely easy and also makes it easier to deploy to staging servers, but maybe deploying locally would be a better option to solve this issue...

**Comment by Deadpikle** [comment]
@akjackson1 Ah, ok, I see. I'll assume then that there's no SSH/similar access on the server? It looks like DeployHQ [has SSH commands (link)](https://www.deployhq.com/support/ssh-commands), but doing that might just be hitting an easy problem with an over engineered solution, and it also would depend on wherever you're doing the shared hosting.

**Comment by akjackson1** [comment]
@Deadpikle I do have SSH access, though I just spoke with tech support and they indicated that the only option would be to upgrade to their VPS solution which is 10 times the price. I'm open to switching to another provider if you're aware of one that allows Composer to be used.

**Comment by akjackson1** [comment]
I've updated this issue now that I found a way to install Composer on out shared hosting 😃

**Comment by asarmiento** [comment]
@akjackson1 excelente que haya encontrado una solución, pero también hay servidores compartidos que si dan acceso por SSH, como webfaction, a2hosting de los que yo conozco

**Comment by d-leonid** [comment]
Hi There
I have setup Twig on my local ( 1 point ) following by doc ( https://github.com/kenjis/codeigniter-ss-twig ) . 

So need change all our current html's ( view ) to twig files ?

**Comment by akjackson1** [comment]
@d-leonid wonderful! Yes that would be the next step. If you get stuck or feel overwhelmed with that part, just create a pull request and others can help!

**Comment by d-leonid** [comment]
@akjackson1 
I should create new branch for this task ?

**Comment by akjackson1** [comment]
@d-leonid yes that is correct. The master branch is actually locked and all changes you make must be under a new branch. You should create a new branch for each new task.

**Comment by d-leonid** [comment]
@akjackson1
okay 
Thank you

**Comment by akjackson1** [comment]
Closing this since we're now managing all our tasks on [Trello](https://trello.com/invite/b/cCdSmpc0/4527547fa5dedeee84a0ccae33d08865/adventist-commons-development).
