### ISSUE TITLE
Daily email digest of changes

### ISSUE THREAD

**Issue by akjackson1** [AdventistCommons/adventistcommons.org#9]
A daily email digest should be sent to contributors of projects

- [ ] Cron job function
- [ ] Mailjet template
- [ ] Breakdown commits, approvals, and revision requests based on section and users

E.g.

**Chapter 1**
Adam Jackson committed 3 translations
Bob Jones approved 2 translations

**Comment by dallas** [comment]
Is this different than the email notifications that GitHub sends out when you follow a repo?

**Comment by davrv93** [comment]
What I use for this kind of tasks is a Celery background project, it works with workers and a broker message service, what I did its an API that receives the html content (that could be the Mailjet template HTML ) and sends the email in background. Everytime that is needed the API should be invoked.

Tell me what you think and I can create a project in python that fulfills this function

**Comment by akjackson1** [comment]
As I've thought about this some more, for our purposes I think it will suffice to simply have a "restore" function on the revisions section. This would allow a reviewer to choose which version to use if two translations were submitted at the same time.

**Comment by akjackson1** [comment]
Closing this since we're now managing all our tasks on [Trello](https://trello.com/invite/b/cCdSmpc0/4527547fa5dedeee84a0ccae33d08865/adventist-commons-development).
